//! Runtime support for weak-link stubs generated by `weaklink_build`.
//!
//! A generated stub crate exposes the following static values:
//!
//! - one [`Library`], whose name is set in `weaklink_build::Config`; and
//! - one [`Group`] for each symbol group passed to `weaklink_build::Config::add_symbol_group`.
//!
//! Use the [`Library`] to load the target dynamic library, then call [`Group::resolve`] before using the symbols in a
//! group. A successful call returns a [`GroupResolved`] token. Keep that token alive while calling the corresponding
//! functions.
//!
//! # Checked mode
//!
//! The `checked` feature is a debugging aid for finding code that calls optional symbols without holding a successful
//! resolution token. While a [`GroupResolved`] token is alive, the symbols in its group remain callable. When the last
//! active token covering a symbol is dropped, checked mode clears that symbol's stub pointer. Calling the stub afterward
//! aborts the process.
//!
//! A symbol may belong to more than one group. It remains callable while a token for any of those groups is alive. Use
//! [`GroupResolved::mark_permanent`] for required symbols that should remain callable for the rest of the process.
//!
//! ## Example
//! ```rust,ignore
//! // build.rs
//! use weaklink_build::{Config, SymbolStub};
//!
//! fn main() {
//!     let mut config = Config::new("stub");
//!     config.add_symbol_group("base", vec![SymbolStub::new("base_api")]).unwrap();
//!     config.add_symbol_group("optional", vec![SymbolStub::new("optional_api")]).unwrap();
//!     ...
//! }
//! ```
//! ```rust,ignore
//! // main.rs
//! extern "C" {
//!     fn base_api();
//!     fn optional_api();
//! }
//!
//! fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     stub::library.load_from(std::path::Path::new("path/to/the/dynamic/library"))?;
//!
//!     // Keep required symbols resolved for the lifetime of the process.
//!     stub::base.resolve()?.mark_permanent();
//!     unsafe { base_api(); }
//!
//!     // Optional symbols can be called while the resolution token is alive.
//!     let token = stub::optional.resolve()?;
//!     unsafe { optional_api(); }
//!     drop(token);
//!
//!     // This call aborts the process in checked mode.
//!     unsafe { optional_api(); }
//!
//!     Ok(())
//! }
//! ```

mod group;
pub mod loading;

use std::{
    cell::UnsafeCell,
    ffi::CStr,
    mem,
    path::Path,
    sync::atomic::{AtomicUsize, Ordering},
};

pub use group::{Group, GroupResolved};
pub use loading::{Address, DylibHandle};

/// The error type returned by loading and symbol-resolution operations.
pub type Error = Box<dyn std::error::Error>;

#[cfg(feature = "checked")]
use std::sync::{Mutex, MutexGuard, OnceLock};

/// Controls loading and symbol resolution for one weakly linked dynamic library.
#[repr(C)]
pub struct Library {
    handle: AtomicUsize,
    dylib_names: &'static [&'static str],
    symbol_names: &'static [&'static CStr],
    symbol_table: &'static [Address],

    // Must initialize this stuff lazily, so we can have a const constructor.
    #[cfg(feature = "checked")]
    checked_state: OnceLock<Mutex<CheckedState>>,
}

#[cfg(feature = "checked")]
struct CheckedState {
    asserted: Box<[u32]>,
}

impl Library {
    #[doc(hidden)]
    pub const fn new(
        dylib_names: &'static [&'static str],
        symbol_names: &'static [&'static CStr],
        symbol_table: &'static [Address],
    ) -> Library {
        Library {
            handle: AtomicUsize::new(0),
            dylib_names,
            symbol_names,
            symbol_table,
            #[cfg(feature = "checked")]
            checked_state: OnceLock::new(),
        }
    }

    /// Loads the library using the candidate names configured at build time.
    ///
    /// Candidate names are tried in order. Returns an error if this [`Library`] already has a handle or none of the
    /// candidates can be loaded.
    pub fn load(&self) -> Result<DylibHandle, Error> {
        let raw_handle = self.handle.load(Ordering::Acquire);
        if raw_handle != 0 {
            return Err("Already loaded.".into());
        } else {
            for name in self.dylib_names {
                if let Ok(handle) = loading::load_library(Path::new(name)) {
                    self.handle.store(handle.0, Ordering::Release);
                    return Ok(handle);
                }
            }
        }
        Err("Library not found.".into())
    }

    /// Loads the dynamic library at `path`.
    ///
    /// Returns an error if this [`Library`] already has a handle or the dynamic library cannot be loaded.
    pub fn load_from(&self, path: &Path) -> Result<DylibHandle, Error> {
        let raw_handle = self.handle.load(Ordering::Acquire);
        if raw_handle != 0 {
            Err("Already loaded.".into())
        } else {
            match loading::load_library(path) {
                Ok(handle) => {
                    self.handle.store(handle.0, Ordering::Release);
                    Ok(handle)
                }
                Err(err) => Err(err),
            }
        }
    }

    /// Sets an existing dynamic-library handle.
    ///
    /// The handle may be obtained via [`loading::load_library`] or from platform-specific APIs.
    /// It must remain valid for as long as generated stubs may be called.
    pub fn set_handle(&self, handle: DylibHandle) {
        self.handle.store(handle.0, Ordering::Release);
    }

    /// Returns the current dynamic-library handle, if one was loaded or supplied with [`Library::set_handle`].
    pub fn handle(&self) -> Option<DylibHandle> {
        let raw_handle = self.handle.load(Ordering::Acquire);
        if raw_handle != 0 {
            Some(DylibHandle(raw_handle))
        } else {
            None
        }
    }

    // Make sure the library is loaded, or panic.
    fn ensure_loaded(&self) -> DylibHandle {
        match self.handle() {
            Some(handle) => handle,
            None => match self.load() {
                Ok(handle) => handle,
                Err(err) => panic!("{}", err),
            },
        }
    }

    // Resolve symbol address and update its entry in the symbol table.
    fn resolve_symbol(&self, sym_index: u32) -> Result<Address, Error> {
        unsafe {
            let entry = self.symbol_table_entry(sym_index);
            let handle = self.ensure_loaded();
            let sym_name = self.symbol_names[sym_index as usize];
            let address = loading::find_symbol(handle, sym_name)?;
            entry.write(address);
            Ok(address)
        }
    }

    // Get a reference to the symbol pointer at the specified index.
    unsafe fn symbol_table_entry(&self, sym_index: u32) -> *mut Address {
        let ptr: &UnsafeCell<Address> = mem::transmute(&self.symbol_table[0]);
        ptr.get().offset(sym_index as isize) as *mut Address
    }
}

#[cfg(not(feature = "checked"))]
impl Library {
    fn assert_resolved(&self, _sym_indices: &[u32]) {}

    fn deassert_resolved(&self, _sym_indices: &[u32]) {}
}

#[cfg(feature = "checked")]
impl Library {
    fn get_checked_state(&self) -> MutexGuard<CheckedState> {
        let mutex = self.checked_state.get_or_init(|| {
            Mutex::new(CheckedState {
                asserted: Self::boxed_slice(self.symbol_table.len()),
            })
        });
        mutex.lock().unwrap()
    }

    fn assert_resolved(&self, sym_indices: &[u32]) {
        let mut checked_state = self.get_checked_state();
        for sym_index in sym_indices {
            checked_state.asserted[*sym_index as usize] += 1;
        }
    }

    fn deassert_resolved(&self, sym_indices: &[u32]) {
        let mut checked_state = self.get_checked_state();
        for sym_index in sym_indices {
            checked_state.asserted[*sym_index as usize] -= 1;
            if checked_state.asserted[*sym_index as usize] == 0 {
                // All threads have de-asserted, so no one should be using this entry.
                unsafe {
                    self.symbol_table_entry(*sym_index).write(0);
                }
            }
        }
    }

    fn boxed_slice<T: Copy + Default>(size: usize) -> Box<[T]> {
        let mut v = Vec::<T>::with_capacity(size);
        v.resize(size, Default::default());
        v.into_boxed_slice()
    }
}
